INSERT INTO LEAVE_APPLICATION(ID,LEAVE_TYPE,EMP_ID,LEAVE_DAYS) VALUES(99,'AL',1,2);
INSERT INTO LEAVE_APPLICATION(ID,LEAVE_TYPE,EMP_ID,LEAVE_DAYS) VALUES(100,'ML',1,7);
INSERT INTO LEAVE_APPLICATION(ID,LEAVE_TYPE,EMP_ID,LEAVE_DAYS) VALUES(101,'CL',1,5);